# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Git.Git
PackageVersion: 2.47.0.2
PackageLocale: en-US
Publisher: The Git Development Community
PublisherUrl: https://gitforwindows.org/
PublisherSupportUrl: https://github.com/git-for-windows/git/issues
Author: Johannes Schindelin
PackageName: Git
PackageUrl: https://gitforwindows.org/
License: GPL-2.0
LicenseUrl: https://raw.githubusercontent.com/git-for-windows/git/main/COPYING
Copyright: Copyright (C) Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/git-for-windows/git/main/COPYING
ShortDescription: Git for Windows focuses on offering a lightweight, native set of tools that bring the full feature set of the Git SCM to Windows while providing appropriate user interfaces for experienced Git users and novices alike.
Description: Git for Windows focuses on offering a lightweight, native set of tools that bring the full feature set of the Git SCM to Windows while providing appropriate user interfaces for experienced Git users and novices alike.
Moniker: git
Tags:
- cli
- command-line
- commandline
- cross-platform
- dvcs
- foss
- open-source
- tool
- utility
- vcs
ReleaseNotes: |-
  Changes since Git for Windows v2.47.0 (October 8th 2024)Bug Fixes
  - A regression in v2.47.0 where git maintenance start crashed immediately was fixed.
  - A regression where clones, fetches and pushes via SSH would dead-lock was fixed.
  - As of Git for Windows v2.47.0, Scalar was supposed to enable an optimized push algorithm, but for a typo didn't, which was fixed.
  - A few documentation and other, minor bug fixes from upstream Git were integrated into Git for Windows early.
  Filename | SHA-256
  -------- | -------
  Git-2.47.0.2-64-bit.exe | 83c618dcc50b63f0f7afc86a7a125169bd59559ff680683f1d915c45e05ff4cc
  Git-2.47.0.2-32-bit.exe | b798dc1ff11afe912994e0e7d0b538edbbd291e666fdc6f34fa4cb19547aefc7
  PortableGit-2.47.0.2-64-bit.7z.exe | c77368a8f6ccbd43bde0df0ab603133ce885407a018787d6f1971e040590f1ab
  PortableGit-2.47.0.2-32-bit.7z.exe | 71d7de445ce2412c0344f5258dec4a51cac3b4b536b0d68c8e753729d429d365
  MinGit-2.47.0.2-64-bit.zip | c4a5d3a2adda98b25fe59349733fca56b3843360b962dba5535282a9d8120b31
  MinGit-2.47.0.2-32-bit.zip | 59748b3193b6f27849e35ee76165d53f47a5a205a4cd83e926800570aeaf5aa2
  MinGit-2.47.0.2-busybox-64-bit.zip | 672aa54dd79d35baa75df934e2bb6faad5b9f45a99339b1dbd5a1fb2f8b44348
  MinGit-2.47.0.2-busybox-32-bit.zip | 94ff74c2c7f68a5093b57c527398fe176230adadb71c25722f0c43a5de611f7b
  Git-2.47.0.2-64-bit.tar.bz2 | b6ca6dcd5c818396faa57e06e10489aed3e16396317475ca8e88e30e4eb2e3c5
  Git-2.47.0.2-32-bit.tar.bz2 | d861cdef6ef1c93f412eb6e5fa766973a6eee5f8a08973ac4a396bb235c3d489
ReleaseNotesUrl: https://github.com/git-for-windows/git/releases/tag/v2.47.0.windows.2
ManifestType: defaultLocale
ManifestVersion: 1.6.0
